### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MrGarlic1** [MrGarlic1/brb#4]
This is not really a direct roadmap, mostly just tracking features that are planned. also these will be done in no particular order

### Code Tasks
- [x] Update descriptions for trains to replace "shot" with another term
- [x] Improve code organization (split botutils.py into trains/response/utility files)
- [x] Add additional numbers and info to train stats function
- [ ] Fix auto-complete for response removal to show mentions properly
- [ ] Train backup/restore automatically

### Repo Tasks
- [ ] Build windows .exe
- [ ] Documentation
- [x] Simplify build from source process (improve organization of non-src files)
